# Default values for node-express-app.

# Deployment values
replicaCount: 2

container:
  image: piterbog/node-express-app:1.0.0
  port : 8080


# Service values
labels:
  env: staging
  owner: PiterKononihin

# type LoadBalancer
ports:
  protocol: TCP
  port: 8080
  targetPort: 8080

service:
  type: LoadBalancer
  externalTrafficPolicy: Local

# HorizontalPodAutoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80