# Default values for node-express-app.

# Deployment values
container:
  image: us-central1-docker.pkg.dev/storm-shadow-453608/prod-node-express-app/node-express-app:production        
  port : 8080
resources:
  requests:
    cpu: "250m"        
    memory: "256Mi"    
  limits:
    cpu: "500m"        
    memory: "512Mi" 
# pull secret 
imagePullSecret: gcp-artifact-secret

# Service values
labels:
  env: staging
  owner: PiterKononihin

# type LoadBalancer
ports:
  protocol: TCP
  port: 8080
  targetPort: 8080

service:
  type: LoadBalancer

# HorizontalPodAutoscaler
hpa:
  enable: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
