# Default values for node-express-app.

# Deployment values
container:
  image: piterbog/node-express-app:1.0.0
  port : 8080


# Service values
labels:
  env: staging
  owner: PiterKononihin

# type LoadBalancer
ports:
  protocol: TCP
  port: 8080
  targetPort: 8080

service:
  type: LoadBalancer

# HorizontalPodAutoscaler
hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
